on:
  pull_request:

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.6.0

      - run: pnpm i
      - run: pnpm test
        env:
          TEST_REPORTER: junit
          TEST_REPORTER_DESTINATION: test-results.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/test-results.xml'
          check_name: Test report
          comment: true
          include_passed: true
          detailed_summary: true
          check_title_template: "{{SUITE_NAME}}/{{TEST_NAME}}"
